name: absensi_admin
description: A new Flutter project for managing attendance.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.70.0
  provider: ^6.1.2
  supabase_flutter: ^2.5.9
  http: ^1.2.2
  intl: ^0.20.2
  csv: ^6.0.0
  path_provider: ^2.0.11
  open_file: ^3.2.1
  pdf: ^3.10.8
  printing: ^5.11.1
  postgrest: 2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true